
import { QuizQuestion, ExamHistory } from './types';

export const MOCK_EXAM_HISTORY: ExamHistory[] = [
  // Fix: Added 'type' property to satisfy ExamHistory interface
  { id: '1', name: 'Simulacro DGAC #24', date: 'Hoy', score: 80, totalQuestions: 35, passed: true, type: 'official' },
  // Fix: Added 'type' property to satisfy ExamHistory interface
  { id: '2', name: 'Simulacro DGAC #23', date: 'Ayer', score: 62, totalQuestions: 35, passed: false, type: 'official' },
  // Fix: Added 'type' property to satisfy ExamHistory interface
  { id: '3', name: 'Meteo Focalizado', date: '22 May', score: 100, totalQuestions: 10, passed: true, type: 'fast' },
];

// BANCO COMPLETO DE 100 PREGUNTAS (DGAC SEPTIEMBRE 2024)
export const BANCO_PREGUNTAS_REALES: QuizQuestion[] = [
  { id: '1', category: "Meteorología", text: "AL AUMENTAR LA ALTURA, LA DENSIDAD DEL AIRE DISMINUYE", options: ["VERDADERO", "FALSO"], correctIndex: 0, explanation: "A mayor altitud, la presión disminuye, lo que hace que las moléculas de aire se expandan y la densidad baje." },
  { id: '2', category: "Seguridad", text: "PREVIO AL VUELO ES RESPONSABILIDAD DEL OPERADOR DETERMINAR SI EL RPA ESTÁ EN CONDICIONES SEGURAS.", options: ["VERDADERO", "FALSO"], correctIndex: 0, explanation: "Es responsabilidad primaria del operador asegurar la aeronavegabilidad antes del despegue." },
  { id: '3', category: "DAN 151", text: "PASOS PARA OBTENCIÓN DE PERMISO DE VUELO SOBRE ÁREA POBLADA:", options: ["SÓLO PERMISO DEL DUEÑO", "SOLICITUD DGAC, CARTA DEL DUEÑO, ANÁLISIS DE RIESGO Y KMZ", "INFORMAR AL CENTRO DE CONTROL", "SOLO NECESITA KMZ"], correctIndex: 1, explanation: "Se requiere un expediente completo con análisis de riesgo y autorizaciones según DAN 151." },
  { id: '4', category: "Aerodinámica", text: "LA FUERZA QUE IMPULSA LA AERONAVE HACIA ADELANTE SE DENOMINA:", options: ["SUSTENTACIÓN", "PESO", "EMPUJE", "RESISTENCIA"], correctIndex: 2, explanation: "El empuje o tracción es la fuerza motriz que vence la resistencia al avance." },
  { id: '5', category: "Meteorología", text: "EN EL METAR '04/03', LA TEMPERATURA DEL PUNTO DE ROCÍO ES:", options: ["4 GRADOS", "3 GRADOS", "7 GRADOS", "1 GRADO"], correctIndex: 1, explanation: "En el código METAR, el segundo valor tras la barra es el punto de rocío." },
  { id: '6', category: "DAN 151", text: "LA DURACIÓN DE LA CREDENCIAL DE OPERADOR DE RPA ES DE:", options: ["12 MESES", "24 MESES", "36 MESES", "60 MESES"], correctIndex: 1, explanation: "La vigencia estándar de la credencial otorgada por la DGAC es de 2 años." },
  { id: '7', category: "DAN 91", text: "DISTANCIA MÍNIMA PARA OPERAR EN PROXIMIDADES DE AERÓDROMOS:", options: ["2 KM", "5 KM", "8 KM", "10 KM"], correctIndex: 2, explanation: "La restricción general es de 8 km (5 NM) para proteger el tráfico tripulado." },
  { id: '8', category: "Aerodinámica", text: "SI SE EXCEDE EL ÁNGULO CRÍTICO DE ATAQUE, EL ALA ENTRA EN:", options: ["ASCENSO RÁPIDO", "PÉRDIDA (STALL)", "VELOCIDAD DE CRUCERO", "ESTABILIDAD"], correctIndex: 1, explanation: "Al exceder este ángulo, el flujo de aire se desprende y la sustentación cae bruscamente." },
  { id: '9', category: "Meteorología", text: "CAPA DE LA ATMÓSFERA DONDE OCURREN LOS FENÓNOS METEOROLÓGICOS:", options: ["ESTRATÓSFERA", "TROPOSFERA", "MESÓSFERA", "EXÓSFERA"], correctIndex: 1, explanation: "La troposfera contiene el vapor de agua y los cambios climáticos." },
  { id: '10', category: "Seguridad", text: "UN RPA DE 5 KG SOBRE UNA MULTITUD REQUIERE DISPOSITIVO DE SEGURIDAD (PARACAÍDAS):", options: ["SÍ", "NO"], correctIndex: 0, explanation: "Las operaciones sobre áreas pobladas exigen mitigación de riesgos catastróficos." },
  { id: '11', category: "DAN 151", text: "DURANTE LA OPERACIÓN, EL PILOTO DEBE PORTAR:", options: ["MANUAL DEL DRON", "CREDENCIAL Y AUTORIZACIÓN DE VUELO", "SÓLO CÉDULA IDENTIDAD", "FACTURA DE COMPRA"], correctIndex: 1, explanation: "Son los documentos que validan la legalidad del vuelo ante fiscalización." },
  { id: '12', category: "DAN 91", text: "¿TIENEN LAS AERONAVES TRIPULADAS PRIORIDAD SOBRE LOS RPA?", options: ["SÍ, SIEMPRE", "SÓLO SI SON COMERCIALES", "NO, EL RPA TIENE PRIORIDAD", "SÓLO EN EMERGENCIAS"], correctIndex: 0, explanation: "Regla básica: el dron siempre cede el paso a aeronaves tripuladas." },
  { id: '13', category: "Aerodinámica", text: "PUNTO DONDE SE APLICA LA FUERZA DE SUSTENTACIÓN:", options: ["CENTRO DE GRAVEDAD", "CENTRO DE PRESIÓN", "BORDE DE SALIDA", "FOCO"], correctIndex: 1, explanation: "El centro de presión es el punto donde actúa la resultante aerodinámica." },
  { id: '14', category: "Meteorología", text: "EN UN METAR, 'NOSIG' SIGNIFICA:", options: ["NO HAY SEÑAL", "SIN CAMBIOS SIGNIFICATIVOS PREVISTOS", "NIEBLA", "SIN VIENTO"], correctIndex: 1, explanation: "Indica que no se esperan cambios meteorológicos importantes en las próximas 2 horas." },
  { id: '15', category: "DAN 151", text: "PESO MÁXIMO DE DESPEGUE BAJO DAN 151 EN ÁREAS POBLADAS:", options: ["6 KG", "25 KG", "50 KG", "10 KG"], correctIndex: 1, explanation: "La norma regula hasta 25 kg para operaciones de interés público en zonas pobladas." },
  { id: '16', category: "Seguridad", text: "EL VUELO VLOS SIGNIFICA:", options: ["VUELO POR INSTRUMENTOS", "VUELO CON VISIÓN DIRECTA DEL OPERADOR", "VUELO AUTÓNOMO", "VUELO NOCTURNO"], correctIndex: 1, explanation: "Visual Line of Sight: mantener el contacto visual directo con la aeronave." },
  { id: '17', category: "DAN 91", text: "EL RPA NO DEBE REPRESENTAR PELIGRO PARA:", options: ["PERSONAS O PROPIEDAD EN SUPERFICIE", "SÓLO OTRAS AERONAVES", "SÓLO EL PILOTO", "ANIMALES SALVAJES"], correctIndex: 0, explanation: "La seguridad de terceros en tierra es una prioridad de la reglamentación." },
  { id: '18', category: "Meteorología", text: "EL MOVIMIENTO VERTICAL DEL AIRE SE DENOMINA:", options: ["VIENTO", "CORRIENTE", "RÁFAGA", "BRISA"], correctIndex: 1, explanation: "El viento es horizontal; los movimientos verticales son corrientes (térmicas)." },
  { id: '19', category: "Aerodinámica", text: "LAS CUATRO FUERZAS EN VUELO SON:", options: ["PESO, EMPUJE, SUSTENTACIÓN Y RESISTENCIA", "VELOCIDAD, MASA, GIRO Y CALOR", "GRAVEDAD, VIENTO, POTENCIA Y FRICCIÓN", "INERCIA, PESO, CARGA Y EMPUJE"], correctIndex: 0, explanation: "Son las fuerzas que definen el equilibrio de cualquier aeronave." },
  { id: '20', category: "DAN 151", text: "LA TARJETA DE REGISTRO DEL RPA ES OBLIGATORIA:", options: ["SÍ", "SÓLO SI ES PROFESIONAL", "SÓLO SI PESA MÁS DE 10 KG", "NO"], correctIndex: 0, explanation: "Toda aeronave bajo DAN 151 debe estar inscrita en el registro institucional de la DGAC." },
  { id: '21', category: "DAN 151", text: "ALTURA MÁXIMA DE OPERACIÓN PERMITIDA:", options: ["120 METROS (400 PIES)", "150 METROS", "200 METROS", "SIN LÍMITE"], correctIndex: 0, explanation: "Límite estándar para separar el tráfico RPA del tripulado." },
  { id: '22', category: "Meteorología", text: "EL BARÓMETRO SIRVE PARA MEDIR:", options: ["VIENTO", "HUMEDAD", "PRESIÓN ATMOSFÉRICA", "TEMPERATURA"], correctIndex: 2, explanation: "Fundamental para el cálculo de altitud y conocimiento del clima." },
  { id: '23', category: "Seguridad", text: "SI PIERDE EL CONTACTO VISUAL CON EL RPA DEBE:", options: ["ESPERAR", "RECUPERAR LA LÍNEA DE VISIÓN O ATERRIZAR SEGÚN PROCEDIMIENTO", "SUBIR MÁS ALTO", "CERRAR LOS OJOS"], correctIndex: 1, explanation: "Si se pierde VLOS, la operación deja de ser segura." },
  { id: '24', category: "Aerodinámica", text: "LA SUSTENTACIÓN SE GENERA POR:", options: ["DIFERENCIA DE PRESIÓN ENTRE EXTRADÓS E INTRADÓS", "SOLO POR LA POTENCIA DEL MOTOR", "POR EL PESO DEL AIRE", "POR LA GRAVEDAD"], correctIndex: 0, explanation: "Explicado por el principio de Bernoulli y la tercera ley de Newton." },
  { id: '25', category: "DAN 151", text: "¿QUÉ ES UN ÁREA POBLADA?", options: ["CIUDADES O ASENTAMIENTOS HUMANOS", "ZONAS RURALES VACÍAS", "SÓLO SANTIAGO", "SÓLO AEROPUERTOS"], correctIndex: 0, explanation: "Cualquier zona con concentración de personas y estructuras." },
  { id: '26', category: "DAN 91", text: "TIEMPO DE ABSTINENCIA DE ALCOHOL ANTES DE VOLAR:", options: ["2 HORAS", "8 HORAS", "24 HORAS", "12 HORAS"], correctIndex: 1, explanation: "Norma de seguridad aeronáutica para evitar deterioro de facultades." },
  { id: '27', category: "Meteorología", text: "METAR 'SKC' SIGNIFICA:", options: ["CIELO DESPEJADO", "NUBES BAJAS", "TORMENTA", "NIEBLA"], correctIndex: 0, explanation: "Sky Clear: ausencia total de nubes." },
  { id: '28', category: "Seguridad", text: "EL FAILSAFE DEBE CONFIGURARSE PARA:", options: ["VOLAR MÁS LEJOS", "VOLVER A CASA O ATERRIZAR ANTE PÉRDIDA DE MANDO", "HACER PIRUETAS", "APAGAR EL DRON EN EL AIRE"], correctIndex: 1, explanation: "Es el mecanismo de seguridad ante pérdida de señal." },
  { id: '29', category: "DAN 151", text: "EL PARACAÍDAS ES OBLIGATORIO PARA OPERAR SOBRE PERSONAS:", options: ["SÍ", "SÓLO SI EL PILOTO QUIERE", "SÓLO EN VUELOS DE NOCHE", "NO"], correctIndex: 0, explanation: "Es un requisito técnico de mitigación de daños en zonas pobladas." },
  { id: '30', category: "Aerodinámica", text: "MOVIMIENTO SOBRE EL EJE LONGITUDINAL:", options: ["CABECEO", "ALABEO", "GUIÑADA", "GIRO"], correctIndex: 1, explanation: "Es el movimiento de inclinación lateral (Roll)." },
  { id: '31', category: "Meteorología", text: "GRADIENTE TÉRMICO VERTICAL ESTÁNDAR:", options: ["1°C / 1000 FT", "2°C / 1000 FT", "5°C / 1000 FT", "3°C / 500 FT"], correctIndex: 1, explanation: "La temperatura baja 2°C por cada 1000 pies de ascenso." },
  { id: '32', category: "DAN 91", text: "¿QUIÉN ES RESPONSABLE FINAL DE LA OPERACIÓN?", options: ["DGAC", "EL PILOTO A DISTANCIA", "EL FABRICANTE", "EL DUEÑO DEL CAMPO"], correctIndex: 1, explanation: "El piloto al mando tiene la autoridad y responsabilidad final." },
  { id: '33', category: "DAN 151", text: "DISTANCIA MÍNIMA A INCENDIOS FORESTALES:", options: ["1 KM", "3 KM", "8 KM (5 NM)", "10 KM"], correctIndex: 2, explanation: "Para no interferir con aviones cisterna y helicópteros de emergencia." },
  { id: '34', category: "Aerodinámica", text: "EFECTO DEL VIENTO DE COLA EN EL DESPEGUE:", options: ["ACORTA LA PISTA", "ALERGA LA DISTANCIA DE DESPEGUE", "NO AFECTA", "SUBE MÁS RÁPIDO"], correctIndex: 1, explanation: "Reduce la velocidad relativa del aire, necesitando más espacio para generar sustentación." },
  { id: '35', category: "Seguridad", text: "TRANSPORTE SEGURO DE BATERÍAS LIPO:", options: ["TOTALMENTE CARGADAS", "BOLSAS IGNÍFUGAS LIPO-SAFE", "EN EL BOLSILLO", "CON AGUA"], correctIndex: 1, explanation: "Previene incendios por cortocircuito o daño físico." },
  { id: '36', category: "DAN 151", text: "SOLICITUD DE VUELO CON ANTICIPACIÓN DE:", options: ["24 HORAS", "5 DÍAS HÁBILES", "10 DÍAS HÁBILES", "1 MES"], correctIndex: 1, explanation: "Plazo administrativo mínimo para coordinar espacio aéreo." },
  { id: '37', category: "Meteorología", text: "VISIBILIDAD EN NIEBLA ES MENOR A:", options: ["1000 METROS", "5000 METROS", "8000 METROS", "100 METROS"], correctIndex: 0, explanation: "Si es mayor a 1000m se considera neblina o bruma." },
  { id: '38', category: "Aerodinámica", text: "MOVIMIENTO SOBRE EL EJE VERTICAL:", options: ["ALABEO", "CABECEO", "GUIÑADA", "ASCENSO"], correctIndex: 2, explanation: "La guiñada (Yaw) es el giro de la nariz a los lados." },
  { id: '39', category: "DAN 91", text: "¿SE PUEDEN LANZAR OBJETOS DESDE UN RPA?", options: ["SÍ", "SÓLO SI SON LIVIANOS", "NO, SALVO AUTORIZACIÓN", "SÓLO EN EL CAMPO"], correctIndex: 2, explanation: "Prohibido por riesgo a personas y navegación aérea." },
  { id: '40', category: "Seguridad", text: "EL ÍNDICE Kp SE REFIERE A:", options: ["PRESIÓN", "ACTIVIDAD GEOMAGNÉTICA", "VIENTO", "LLUVIA"], correctIndex: 1, explanation: "Afecta la precisión del GPS y la brújula electrónica." },
  { id: '41', category: "Meteorología", text: "CAVOK SIGNIFICA:", options: ["VIENTO FUERTE", "BUEN TIEMPO Y VISIBILIDAD", "TORMENTA", "NIEVE"], correctIndex: 1, explanation: "Ceiling and Visibility OK." },
  { id: '42', category: "Seguridad", text: "DESORIENTACIÓN ESPACIAL ES:", options: ["PERDER EL DRON", "INCAPACIDAD DE PERCIBIR POSICIÓN Y ACTITUD", "FALLA DE GPS", "FATIGA"], correctIndex: 1, explanation: "Fallo sensorial peligroso para el piloto." },
  { id: '43', category: "DAN 151", text: "¿ES OBLIGATORIO EL SEGURO DE DAÑOS?", options: ["SÍ", "NO", "SÓLO PARA EMPRESAS", "SÓLO SI PESA MÁS DE 5 KG"], correctIndex: 0, explanation: "Requisito legal para cubrir responsabilidad civil." },
  { id: '44', category: "Aerodinámica", text: "EFECTO SUELO OCURRE A:", options: ["ALTURAS GRANDES", "BAJA ALTURA (CERCANO A ENVERGADURA)", "SÓLO EN EL MAR", "VUELO NOCTURNO"], correctIndex: 1, explanation: "Aumenta sustentación al comprimirse el aire contra el suelo." },
  { id: '45', category: "Meteorología", text: "NUBES CUMULONIMBUS INDICAN:", options: ["BUEN TIEMPO", "TORMENTAS Y TURBULENCIA", "NIEBLA ALTA", "CALOR"], correctIndex: 1, explanation: "Nubes de gran desarrollo vertical muy peligrosas." },
  { id: '46', category: "DAN 91", text: "ZONAS PROHIBIDAS DE VUELO:", options: ["PLAZAS", "RECINTOS MILITARES Y CÁRCELES", "PLAYAS", "BOSQUES"], correctIndex: 1, explanation: "Restricción por seguridad nacional." },
  { id: '47', category: "Seguridad", text: "VORTEX RING STATE ES PELIGROSO EN:", options: ["DESPEGUE", "DESCENSOS VERTICALES RÁPIDOS", "VUELO NIVELADO", "GIROS"], correctIndex: 1, explanation: "El dron entra en su propia turbulencia y cae." },
  { id: '48', category: "DAN 151", text: "PLAZO PARA NOTIFICAR ACCIDENTE:", options: ["12 HORAS", "48 HORAS", "7 DÍAS", "24 HORAS"], correctIndex: 1, explanation: "Obligatorio ante sucesos que afecten seguridad." },
  { id: '49', category: "Aerodinámica", text: "SI EL PESO EXCEDE LA SUSTENTACIÓN:", options: ["SUBE", "BAJA", "SE DETIENE", "ACELERA"], correctIndex: 1, explanation: "Fuerzas desequilibradas hacia abajo." },
  { id: '50', category: "Meteorología", text: "VCFG SIGNIFICA:", options: ["NIEBLA EN LA VECINDAD", "VISIBILIDAD CLARA", "VIENTO FUERTE", "GRANIZO"], correctIndex: 0, explanation: "Indica niebla cerca pero no en el punto exacto." },
  { id: '51', category: "Seguridad", text: "LA FATIGA PRODUCE:", options: ["MEJOR CONCENTRACIÓN", "MENOR TIEMPO DE REACCIÓN", "VISIÓN TÚNEL Y ERRORES", "MÁS ENERGÍA"], correctIndex: 2, explanation: "Deterioro de capacidades psicomotoras." },
  { id: '52', category: "DAN 91", text: "NOTAM ES:", options: ["REGLAMENTO", "AVISO CON INFORMACIÓN TEMPORAL CRÍTICA", "MODELO DE DRON", "CÓDIGO DE RADIO"], correctIndex: 1, explanation: "Notice to Airmen." },
  { id: '53', category: "Meteorología", text: "HUMEDAD RELATIVA SE MIDE EN:", options: ["GRADOS", "PORCENTAJE", "KILOS", "NUDOS"], correctIndex: 1, explanation: "Cantidad de vapor en relación al máximo posible." },
  { id: '54', category: "Aerodinámica", text: "TIMÓN DE DIRECCIÓN CONTROLA:", options: ["ALABEO", "CABECEO", "GUIÑADA", "PESO"], correctIndex: 2, explanation: "Movimiento sobre el eje vertical." },
  { id: '55', category: "DAN 151", text: "VUELO NOCTURNO REQUIERE:", options: ["SÓLO BUENA VISTA", "LUCES DE NAVEGACIÓN Y AUTORIZACIÓN", "SÓLO CÁMARA TÉRMICA", "ESTÁ PROHIBIDO"], correctIndex: 1, explanation: "Condiciones especiales de visibilidad y permiso." },
  { id: '56', category: "Seguridad", text: "CRM SIGNIFICA:", options: ["CARGA DE MOTOR", "GESTIÓN DE RECURSOS DE TRIPULACIÓN", "CÓDIGO DE RADIO", "CONTROL REMOTO"], correctIndex: 1, explanation: "Optimización del trabajo humano y técnico." },
  { id: '57', category: "Meteorología", text: "GUST EN METAR SIGNIFICA:", options: ["VIENTO CALMO", "RÁFAGA", "LLUVIA", "NUBES"], correctIndex: 1, explanation: "Incremento súbito de la velocidad del viento." },
  { id: '58', category: "DAN 91", text: "PRIORIDAD DE PASO:", options: ["DRON SOBRE AVIÓN", "AVIÓN SOBRE DRON", "IGUALDAD", "DEPENDE DEL TAMAÑO"], correctIndex: 1, explanation: "La aviación tripulada manda." },
  { id: '59', category: "Aerodinámica", text: "RESISTENCIA INDUCIDA ES:", options: ["POR EL MOTOR", "SUBPRODUCTO DE LA SUSTENTACIÓN", "POR LA FORMA", "POR LA GRAVEDAD"], correctIndex: 1, explanation: "Se genera en las puntas del ala al crear sustentación." },
  { id: '60', category: "Seguridad", text: "SI APARECE AVIÓN TRIPULADO:", options: ["ACERCARSE", "DESCENDER Y LIBERAR ESPACIO", "SUBIR", "SEGUIR"], correctIndex: 1, explanation: "Evitar colisión es la máxima prioridad." },
  { id: '61', category: "DAN 151", text: "DELIMITAR ÁREA DE VUELO SIRVE PARA:", options: ["QUE NO ESCAPE EL DRON", "SEGURIDAD DE TERCEROS EN TIERRA", "SÓLO ESTÉTICA", "ORDENAR BATERÍAS"], correctIndex: 1, explanation: "Controlar el acceso a la zona de riesgo." },
  { id: '62', category: "Meteorología", text: "BKN SIGNIFICA:", options: ["DESPEJADO", "NUBLADO (5-7 OCTAS)", "CUBIERTO", "POCO NUBOSO"], correctIndex: 1, explanation: "Broken: cielo muy cubierto pero con claros." },
  { id: '63', category: "Aerodinámica", text: "MOVIMIENTO SOBRE EJE LATERAL:", options: ["ALABEO", "CABECEO", "GUIÑADA", "PITCH"], correctIndex: 1, explanation: "Es el cabeceo (Pitch)." },
  { id: '64', category: "DAN 91", text: "VELOCIDAD LÍMITE RECOMENDADA:", options: ["50 NUDOS", "87 NUDOS", "150 NUDOS", "30 NUDOS"], correctIndex: 1, explanation: "Límite estándar de seguridad operacional." },
  { id: '65', category: "Seguridad", text: "CONCIENCIA SITUACIONAL ES:", options: ["SABER DÓNDE ESTOY", "SABER QUÉ PASA, POR QUÉ Y QUÉ PASARÁ", "MIRAR EL CELULAR", "TENER GPS"], correctIndex: 1, explanation: "Entendimiento total del entorno de vuelo." },
  { id: '66', category: "Meteorología", text: "PRESIÓN ESTÁNDAR NIVEL MAR:", options: ["1013.2 HPA", "900 HPA", "1026 HPA", "1000 HPA"], correctIndex: 0, explanation: "Valor ISA de referencia." },
  { id: '67', category: "Aerodinámica", text: "ÁNGULO DE ATAQUE ES ENTRE:", options: ["ALA Y SUELO", "CUERDA ALAR Y VIENTO RELATIVO", "MOTOR Y COLA", "GPS Y NORTE"], correctIndex: 1, explanation: "Define la capacidad de sustentación." },
  { id: '68', category: "DAN 151", text: "REGISTRO DE VUELO (BITÁCORA):", options: ["NO ES NECESARIO", "OBLIGATORIO REGISTRAR TIEMPOS Y MANTENCIÓN", "SÓLO SI HAY ACCIDENTE", "SÓLO PARA DRONES DJI"], correctIndex: 1, explanation: "Requisito para trazabilidad de la aeronave." },
  { id: '69', category: "Seguridad", text: "INCENDIO LIPO SE APAGA CON:", options: ["AGUA", "ARENA O EXTINTOR CLASE D/ABC", "SOPLANDO", "MANTA COMÚN"], correctIndex: 1, explanation: "El litio reacciona mal con el agua." },
  { id: '70', category: "Meteorología", text: "DZ EN METAR:", options: ["NIEBLA", "LLOVIZNA", "LLUVIA", "TORMENTA"], correctIndex: 1, explanation: "Drizzle: llovizna fina." },
  { id: '71', category: "DAN 91", text: "FPV SIN OBSERVADOR:", options: ["ESTÁ PERMITIDO", "ESTÁ PROHIBIDO", "SÓLO EN CARRERAS", "SÓLO SI TIENE SENSORES"], correctIndex: 1, explanation: "Se requiere siempre mantener VLOS (directo o con spotter)." },
  { id: '72', category: "Aerodinámica", text: "RESISTENCIA PARÁSITA:", options: ["AYUDA A VOLAR", "POR FRICCIÓN Y FORMA", "DADA POR EL PESO", "POR EL VIENTO"], correctIndex: 1, explanation: "Resistencia que no genera sustentación." },
  { id: '73', category: "Seguridad", text: "IMSAFE EVALÚA:", options: ["EL DRON", "EL ESTADO DEL PILOTO", "EL CLIMA", "LAS BATERÍAS"], correctIndex: 1, explanation: "Checklist de salud y estado mental del piloto." },
  { id: '74', category: "DAN 151", text: "DISTANCIA A AERÓDROMOS NO CONTROLADOS:", options: ["1 KM", "3 KM (2 NM)", "8 KM", "10 KM"], correctIndex: 1, explanation: "Mínimo de seguridad para evitar tráfico local." },
  { id: '75', category: "Meteorología", text: "VIENTO 09015KT:", options: ["DEL NORTE", "DEL ESTE A 15 NUDOS", "DEL OESTE", "CALMO"], correctIndex: 1, explanation: "090 grados es el Este." },
  { id: '76', category: "Aerodinámica", text: "ESTABILIDAD LATERAL ASOCIADA A:", options: ["CABECEO", "ALABEO", "GUIÑADA", "MOTOR"], correctIndex: 1, explanation: "Estabilidad en el eje longitudinal (alabeo)." },
  { id: '77', category: "Seguridad", text: "EFECTO DEL FRÍO EN LIPO:", options: ["MÁS POTENCIA", "MENOR RENDIMIENTO Y VOLTAJE", "NADA", "EXPLOSIÓN"], correctIndex: 1, explanation: "Ralentiza la química interna de la celda." },
  { id: '78', category: "DAN 151", text: "EDAD MÍNIMA OPERADOR:", options: ["12 AÑOS", "18 AÑOS", "21 AÑOS", "15 AÑOS"], correctIndex: 1, explanation: "La mayoría de edad es el estándar legal." },
  { id: '79', category: "Meteorología", text: "EL VIENTO FLUYE DE:", options: ["BAJA A ALTA PRESIÓN", "ALTA A BAJA PRESIÓN", "SUR A NORTE SIEMPRE", "SOLO EN VERTICAL"], correctIndex: 1, explanation: "Buscando el equilibrio de la atmósfera." },
  { id: '80', category: "DAN 91", text: "ESPACIO AÉREO CLASE G:", options: ["CONTROLADO", "NO CONTROLADO", "PROHIBIDO", "RESERVADO"], correctIndex: 1, explanation: "Espacio aéreo donde no se provee control de tránsito." },
  { id: '81', category: "Seguridad", text: "FLYAWAY: ¿QUÉ HACER?", options: ["ESPERAR", "NOTIFICAR A ATC/TORRE SI HAY RIESGO", "BUSCAR OTRO", "IRSE"], correctIndex: 1, explanation: "Es una emergencia de tráfico aéreo." },
  { id: '82', category: "Aerodinámica", text: "BORDE DE SALIDA:", options: ["PARTE DELANTERA", "PARTE TRASERA DEL ALA", "ARRIBA", "ABAJO"], correctIndex: 1, explanation: "Donde el flujo de aire abandona el perfil." },
  { id: '83', category: "Meteorología", text: "TAF ES PRONÓSTICO PARA:", options: ["TODA LA CIUDAD", "UN AERÓDROMO ESPECÍFICO", "UN PAÍS", "EL ESPACIO"], correctIndex: 1, explanation: "Terminal Aerodrome Forecast." },
  { id: '84', category: "DAN 151", text: "CHALECO REFLECTANTE:", options: ["SÓLO MODA", "IDENTIFICAR AL PILOTO AL MANDO", "PARA EL CALOR", "NO SE USA"], correctIndex: 1, explanation: "Seguridad y visibilidad del operador." },
  { id: '85', category: "Seguridad", text: "ALCOHOL EN SANGRE:", options: ["MEJORA EL VUELO", "RETARDA REACCIONES Y JUICIO", "ES PERMITIDO", "DURA 1 HORA"], correctIndex: 1, explanation: "Factor de riesgo crítico." },
  { id: '86', category: "Aerodinámica", text: "MULTIRROTORES GIRAN POR:", options: ["CAMBIO DE RPM EN MOTORES", "MOVIMIENTO DE ALAS", "PESO", "VIENTO"], correctIndex: 0, explanation: "Variación de torque y sustentación por motor." },
  { id: '87', category: "Meteorología", text: "WIND SHEAR ES:", options: ["VIENTO SUAVE", "CAMBIO BRUSCO DE DIRECCIÓN/VELOCIDAD", "NUBES ALTAS", "CALOR"], correctIndex: 1, explanation: "Cortante de viento, muy peligroso." },
  { id: '88', category: "DAN 151", text: "EXAMEN PARA CREDENCIAL:", options: ["SÓLO TEÓRICO", "TEÓRICO Y PRÁCTICO", "SÓLO ENTREVISTA", "NO HAY"], correctIndex: 1, explanation: "Evaluación integral de conocimientos y pericia." },
  { id: '89', category: "Seguridad", text: "DISTANCIA DE FRENADO DEPENDE DE:", options: ["SÓLO EL COLOR", "VELOCIDAD, MASA Y VIENTO", "MARCA DEL DRON", "GPS"], correctIndex: 1, explanation: "La inercia varía según estas variables físicas." },
  { id: '90', category: "Meteorología", text: "TS EN METAR:", options: ["TORMENTA ELÉCTRICA", "NIEVE", "NIEBLA", "TORNADO"], correctIndex: 0, explanation: "Thunderstorm." },
  { id: '91', category: "Aerodinámica", text: "PERFIL ALAR ASIMÉTRICO:", options: ["TIENE CURVATURA", "ES PLANO", "NO VUELA", "ES CUADRADO"], correctIndex: 0, explanation: "Permite mayor sustentación a bajos ángulos de ataque." },
  { id: '92', category: "DAN 91", text: "PRIORIDAD ANTE PARACAIDISTAS:", options: ["TIENE EL DRON", "TIENE EL PARACAIDISTA", "DEPENDE", "NINGUNO"], correctIndex: 1, explanation: "Seguridad de la vida humana siempre primero." },
  { id: '93', category: "Seguridad", text: "SOBRECARGA DE TRABAJO PROVOCA:", options: ["MÁS VELOCIDAD", "ERRORES Y FIJACIÓN", "MEJOR VUELO", "NADA"], correctIndex: 1, explanation: "Saturación del procesamiento cognitivo." },
  { id: '94', category: "Meteorología", text: "NITRÓGENO EN LA ATMÓSFERA:", options: ["21%", "78%", "1%", "50%"], correctIndex: 1, explanation: "Componente mayoritario del aire." },
  { id: '95', category: "DAN 151", text: "ZONA P (PROHIBIDA):", options: ["VUELO LIBRE", "VUELO RESTRINGIDO TOTALMENTE", "SÓLO FIN DE SEMANA", "CON PERMISO MUNICIPAL"], correctIndex: 1, explanation: "Zonas de seguridad máxima donde no se vuela." },
  { id: '96', category: "Aerodinámica", text: "TORQUE SE COMPENSA CON:", options: ["GIRO OPUESTO DE MOTORES (CW/CCW)", "MÁS PESO", "ALAS LARGAS", "BATERÍA GRANDE"], correctIndex: 0, explanation: "Anulación de momentos de rotación." },
  { id: '97', category: "Seguridad", text: "MAINTENANCE LOG ES:", options: ["UN VIDEO", "REGISTRO DE MANTENCIÓN Y REPARACIONES", "DÓNDE SE COMPRÓ", "EL NOMBRE DEL PILOTO"], correctIndex: 1, explanation: "Bitácora técnica de la aeronave." },
  { id: '98', category: "Meteorología", text: "SHRA SIGNIFICA:", options: ["NIEVE", "CHUBASCOS DE LLUVIA", "HURACÁN", "CALMA"], correctIndex: 1, explanation: "Showers of Rain." },
  { id: '99', category: "DAN 91", text: "VOLAR BAJO DROGAS ES:", options: ["DELITO Y FALTA GRAVE", "PERMITIDO", "SÓLO SI ES FIN DE SEMANA", "SIN IMPORTANCIA"], correctIndex: 0, explanation: "Sancionado por el Código Aeronáutico." },
  { id: '100', category: "Seguridad", text: "PRE-FLIGHT CHECKLIST INCLUYE:", options: ["SÓLO LIMPIAR", "VERIFICACIÓN TÉCNICA, ENTORNO Y COMUNICACIONES", "VER EL PRECIO", "NADA"], correctIndex: 1, explanation: "Procedimiento esencial para evitar fallas en vuelo." }
];

export const MATERIAL_ICONS = {
  HOME: 'grid_view',
  METAR: 'cloud_circle',
  PROGRESS: 'bar_chart',
  PROFILE: 'account_circle',
  QUIZ: 'quiz',
  TIMER: 'timer',
  SETTINGS: 'settings',
  ADD: 'add',
  ARROW_BACK: 'arrow_back_ios_new',
  CHEVRON_RIGHT: 'chevron_right',
  CHECK: 'check_circle',
  ERROR: 'error'
};
